version: '3.8'
services:
  client:
    build: ./website
    ports:
      - "5173:80"
    depends_on:
      - server
    networks:
      - app-network

  server:
    build: ./server
    ports:
      - "8000:8000"
    volumes:
      - ./server:/usr/src/app
    environment:
      - NODE_ENV=production
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
